import { useState, useEffect } from 'react';
import { Inter } from "next/font/google";
import axios from 'axios';
// import Header from '../components/layout/Header'
// import Footer from '../components/layout/Footer'
import ProductManagementForm from "./ProductManagementForm";
import { useLoginStatus } from '../../hooks/useLoginStatus';

const inter = Inter({ subsets: ["latin"] });

function ProductManagement() {
    const [productManagementData, setProductManagementData] = useState({});
    const { user } = useLoginStatus();

    useEffect(() => {
        if (user?._id) {
            axios.get(`${process.env.NEXT_PUBLIC_BACKEND_URL}/api/v1/product-management/${user?._id}`)
                .then(res => {
                    setProductManagementData(res.data);
                })
                .catch(err => {
                    setProductManagementData({})
                    console.log(err)
                })
        }
    }, [user?._id])

    return (
        <div className={`${inter.className}`}>
            {/* <Header /> */}
            <div className='bg-white wrapper p-12'>
                <div>
                    <div>

                        {/* <p>{JSON.stringify(productManagementData)}</p> */}

                        <h2 className="text-xl sm:text-2xl md:text-3xl font-bold mb-6 text-bluedark">
                            Welcome to Mylapay’s API World
                        </h2>
                        <p className="mb-4 text-gray-700">
                            This sandbox environment enables you to test Mylapay’s unified payment processing platform from Authentication, Authorization to chargeback cycle.
                        </p>
                        <p className="mb-4 text-gray-700">
                            Both Card-present (POS) and Card-not-present (PG) transactions can be tested in this environment.
                        </p>

                        <p className="mb-4 text-gray-700">
                            Mylapay uses HTTP signature as an authentication method.
                        </p>

                        <p className="mb-4 text-gray-700 font-semibold">
                            The following credentials are required to successfully authenticate and setup the sandbox environment:
                        </p>

                        <ul className="list-decimal list-inside mb-6 text-gray-700">
                            <li className="mb-2">
                                <span className="font-semibold">Unique ID </span> – This ID will be generated by Mylapay for the user. This will be available in the My Profile section. It is non-editable and non-copyable.
                            </li>
                            <li className="mb-2">
                                <span className="font-semibold">Username</span> – The email ID used during signup will be the default username.
                            </li>
                            <li className="mb-2">
                                <span className="font-semibold">API URL </span> – Each of Mylapay’s products has a unique API URL that will be used in sandbox testing.
                            </li>
                            <li className="mb-2">
                                <span className="font-semibold">API Keys</span> – Two keys will be generated, Public Key and Private Key that will be used to authenticate the user. You will be able to download the Public Key and upload it in PEM format.
                            </li>
                        </ul>

                        <div className="bg-bluedark border-l-4 border-primary p-4 mb-6">
                            <p className="text-primary font-semibold">Note:</p>
                            <ul className="list-disc list-inside text-primary">
                                <li className="mb-2">
                                    You will be able to reset your password using the Reset Password option available on the Login Page.
                                </li>
                                <li className="mb-2">
                                    Do not share your API Keys with anyone or on any public platforms. This can pose serious threats for your Mylapay Account.
                                </li>
                                <li className="mb-2">
                                    You will be able to generate API Keys using “Generate Keys” option for each of the products you are choosing to test in this environment.
                                </li>
                            </ul>
                        </div>

                        <ProductManagementForm
                            userId={user?._id}
                            productManagementData={productManagementData}
                            setProductManagementData={setProductManagementData}
                        />

                    </div>
                </div>
            </div>
            {/* <Footer /> */}
        </div>
    )
}

export default ProductManagement